### ISSUE TITLE
Burro dies after one input

### ISSUE THREAD

**Issue by mateig** [yconst/burro#19]
Using the Logitech game pad, I'm able to give one command to the Navio2 (i.e. steering, or throttle), before it dies off and no longer accepts commands. The entire internet connectivity on the raspberry pi fails, even ssh fails.
(It's connected through WiFi)

**Comment by yconst** [comment]
Can you please take a look at the output and post it here? There should be an exception or error of some sort.

Normally if Burro crashes the Pi should remain responsive, and you should be able to maintain ssh connection. It seems peculiar that the whole system crashes..

**Comment by mateig** [comment]
There is no way for me to view to log. The entire RPi 3 crashes, using a screen connected through hdmi shows "No Signal". The red/green light on the RPi are normal (green steadily flashing, solid red). 

I think that as soon as the RPi receives input from the game pad (Logitech F710), the raspberry freezes...

**Comment by yconst** [comment]
Are you able to use Burro without the gamepad? e.g. if you start it up without the gamepad connected, and you select a Keras model for steering, does the servo steer?

Also, have you used the gamepad previously on your Pi? If your Pi freezes completely, it could be a power supply issue. How do you power the Pi?

**Comment by mateig** [comment]
Solved!

The problem was that when the Navio2 gave out a signal, it drew power from the esc, however, I was already powering it through the power port on the Navio2. The conflict of currents made it crash. I removed the cathode from the ESC and attached it directly to the servo for steering.
