### ISSUE TITLE
Colour Artefacts in Recorded Output

### ISSUE THREAD

**Issue by adricl** [yconst/burro#32]
I have been recording frames with my car, however, I am getting strange colours down the bottom. Is this intentional? I have tested the picam using the still images and it's been fine.

![frame_00004_ttl_-95_agl_0_mil_1507080140979](https://user-images.githubusercontent.com/3646505/31162371-b509246c-a928-11e7-80d6-bdcda95bb84a.jpg)

**Comment by yconst** [comment]
That's quite interesting. I've been having the exact same artifacts for some time, and always thought that my camera was playing up! Your experience shows that it's probably an issue of the Picamera library or the camera driver itself when working in some resolutions. I'm going to try with a slightly larger resolution and see how it works.

**Comment by adricl** [comment]
It might be worth abandoning the python picamera library and use the PiCamera as a webcam so we are compatible with other webcams. https://www.linux-projects.org/uv4l/. After looking at it more its quite a bit of work. I cant look into this issue right now as I am about to go on holidays. I can look at it after I come back.

**Comment by yconst** [comment]
This turned out to be due to the selected resolution indeed. Setting a different resolution, such as 160x120 or 120x90 fixes the issue. Thanks for reporting @adricl !
