### ISSUE TITLE
where is config.py?

### ISSUE THREAD

**Issue by f-e-l-i-x** [yconst/burro#43]
Hi,

After installation there is no config.py in /burro/burro. Is it automatically generated? Is there a template I can use?

Thanks,

Felix

**Comment by yconst** [comment]
The configuration files live in the `config/` module. There are two files, `defaults.ini` and `user.ini`. The first one exists by default and the second one is either generated on the fly or by the user. 

Both can be changed but it is more convenient to ad your overrides to the `user.ini` file. Anything in that file will override the defaults.
