### ISSUE TITLE
issue with throttle

### ISSUE THREAD

**Issue by f-e-l-i-x** [yconst/burro#44]
Hi,

I am trying an identical build with a mini-trooper, the same ESC, wide-angle camera, Navio2 and Logitech F710, only minor difference is that I am using a rpi 3 instead of rpi 2. I am using the emlid raspbian jessie image, the stretch image did not work with the install-burro.sh.

The web interface starts and I see the camera feed, steering from the F710 works, but the throttle does not. I cannot start the car, 0 is displayed for throttle on the web interface. Am I missing something simple? In donkey I have to calibrate and enter PWM values for neutral, forward and reverse, is this necessary with burro?

When I start start.sh, I get the following output:
pi@navio:~/burro/burro $ sudo ./start.sh

2018-01-15 07:17:52,489 - Found NAVIO2 HAT
2018-01-15 07:17:52,689 - Gamepad initialized
2018-01-15 07:17:54,694 - Loaded F710 Gamepad module
2018-01-15 07:17:54,724 - Loaded RC module
2018-01-15 07:17:54,729 - Setting up Ackermann car
2018-01-15 07:17:55,774 - PiVideoStream loaded.. .warming camera

/home/pi/burro/local/lib/python2.7/site-packages/picamera/encoders.py:545: PiCameraResolutionRounded: frame size rounded up from 160x120 to 160x128 width, height, fwidth, fheight)))

Exception in thread Thread-3:

Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()

  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)

  File "/home/pi/burro/burro/burro/sensors/cameras.py", line 95, in update
    self.rawCapture, format="rgb", use_video_port=True):

  File "/home/pi/burro/local/lib/python2.7/site-packages/picamera/camera.py", line 1625, in capture_continuous
    camera_port, output_port = self._get_ports(use_video_port, splitter_port)

  File "/home/pi/burro/local/lib/python2.7/site-packages/picamera/camera.py", line 545, in _get_ports
    'The camera is already using port %d ' % splitter_port)

PiCameraAlreadyRecording: The camera is already using port 0 

After this, as I mentioned, the web interface starts, just the throttle does not work.

Hope you can help me,

thanks,

Felix

**Comment by yconst** [comment]
Hi Felix,

The exception is normal and caused by the PiCamera library, so I wouldn't worry.

Regarding your throttle problem, it may be that you are using a different channel for throttle on your RC? You can select the throttle channel in Burro by altering the `throttle_channel` parameter in config.

Also, make sure you have armed the vehicle from yout RC control. Burro requires arming the RC prior to the vehicle moving. The arming channel is set by the `arm_channel` parameter.

Calibration is not required atm. The neutral position is detected at the time of activation of the control. It may be a good idea to implement an extremes calibration mechanism in the near future.

**Comment by f-e-l-i-x** [comment]
Hi,

I don't have an RC control, just the F710, is an RC control necessary in addition? Is there an equivalent to arming if I only use the F710?

Thanks,

Felix

**Comment by f-e-l-i-x** [comment]
Hi,

ok, I have done a few tests:

- connected RC control, channel 4 successfully triggers calibration/arming, but steering and throttle don't work

- connected F710, steering works, but throttle doesn't

- tried the Navio2 PWM test (Servo.py) -> steering servo and motor work

- did Navio2 RC test (RCInput.py), RC signals are received ok

Any ideas? Can I enter PWM ranges somewhere?

Thanks,

Felix

**Comment by yconst** [comment]
Hi,

Sorry I misread your question. So just to clarify, with F710 you hold up arrow down *and* push the top button [like in this figure](https://github.com/yconst/burro/wiki/Control-a-Burro-car-using-the-F710-Gamepad)?

re. RC control, the rest of the channels are ok (i.e. throttle and steering channel)?

**Comment by f-e-l-i-x** [comment]
Hi,

Sorry if I wasn't clear. With the F710, I used the joystick marked "S" in the figure for steering and throttle (throttle didn't work). Pressing F, R or T didn't do anything. I don't remember if I pressed up and the top button at the same time, bit I think I tried that, too. Is the figure to be understood that you have to press up and top button before you can use the joystick?

For RC control I used the RC controller and receiver that came with the car and converted the analogue output from the receiver to PPM using an Arduino, which was connected to the Navio2 (I don't have a different RC controller). 

The Navio2 could read the steering and throttle channels, the output of RCInput.py was between 1000 and 1800 depending on RC controller stick position. However, when used with burro, steering and throttle did not work, but the calibration message came up when channel 4 was activated.

**Comment by yconst** [comment]
Hi,

No problem, the figure could need some improvement. There is an analog button on the top left side of the F710 controller. While pressing F, try pushing that too. Sometimes depending on the motor and ESC just pushing F may not be enough to start the car. Pressing on the analog button as well increases the throttle.

Regarding RC, what RC channels does your Arduino output? Maybe you need to adjust the channel number in Burro config

**Comment by f-e-l-i-x** [comment]
Do you have the F710 in "D" or "X" mode?

**Comment by f-e-l-i-x** [comment]
If I swap the channels in defaults.ini [ackermann_car] then the throttle works, but not the steering

**Comment by f-e-l-i-x** [comment]
which I guess means that the hardware is set up correctly.

Pressing F and/or top left analogue button does not start my car.

**Comment by yconst** [comment]
For F710, I have to check when I get back home. I'll update you.

Re. RC control, one of your channels is probably misconfigured. I'd suggest trying different channels in Burro config until you get the right one.

**Comment by f-e-l-i-x** [comment]
In rover.py "for pilot in self.manual_pilots" is carried out twice, the first time for F710, then for RC. 

As no RC is connected, the throttle value of F710 is overwritten by RC.

If have commented out manual_pilots.append(RC()) in composers.py

Furthermore, I have removed "#" before "self.throttle -= (float(st[12]) - 128.0) / 128.0" in f710.py and changed "-=" to "=-" and removed the section about direction

direction = int(st[2]) queries the left analogue stick, not the digital pad with the four arrows on the (this can be queried with st[8]==255 for up and st[8]==0 for down)

Now it's working!

**Comment by f-e-l-i-x** [comment]
For the record: f710 is set to "X"

**Comment by yconst** [comment]
Great that you got it working! I checked also myself, the pad is in the "X" mode.

The throttle issue what you mentioned is worth investigating – I am going to open an issue on the topic.

It is strange that different gamepad channels work for you. I double checked and the channels seem correct (i.e. the car is moving)
